import type { Metadata } from "next";
import './globals.css';

import { Roboto } from 'next/font/google';

import { cn } from '@/lib/utils';

import { ThemeProvider } from './ThemeProvider';

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(roboto.className, 'bg-light-000 antialiased')}>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
